name: Python CI

on:
  push:
    branches:
      - master   
      - dev  
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt  

    
    # Run tests with pytest and coverage
    - name: Run tests with coverage
      run: |
        pytest --cov=backend --cov-report=term-missing --cov-fail-under=80  # Fail if coverage is below 80%
      continue-on-error: false
    - name: Upload code coverage to GitHub
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml